/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.warung;

import javax.swing.JFrame;
import javax.swing.SwingWorker;

/**
 *
 * @author fahri
 */
public class MainForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainForm.class.getName());

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainDesktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        productListMenu = new javax.swing.JMenuItem();
        productCreateMenu = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        menuCreateTransaction = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout mainDesktopLayout = new javax.swing.GroupLayout(mainDesktop);
        mainDesktop.setLayout(mainDesktopLayout);
        mainDesktopLayout.setHorizontalGroup(
            mainDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 779, Short.MAX_VALUE)
        );
        mainDesktopLayout.setVerticalGroup(
            mainDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 526, Short.MAX_VALUE)
        );

        jMenu1.setText("Login");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Produk");

        productListMenu.setText("Daftar Produk");
        productListMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productListMenuActionPerformed(evt);
            }
        });
        jMenu2.add(productListMenu);

        productCreateMenu.setText("Tambah Produk");
        productCreateMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productCreateMenuActionPerformed(evt);
            }
        });
        jMenu2.add(productCreateMenu);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Transaksi");

        jMenuItem2.setText("Daftar Transaksi");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        menuCreateTransaction.setText("Transaksi Baru...");
        menuCreateTransaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCreateTransactionActionPerformed(evt);
            }
        });
        jMenu3.add(menuCreateTransaction);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainDesktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainDesktop)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        TransactionListForm transactionListForm = new TransactionListForm();
        mainDesktop.add(transactionListForm);
        transactionListForm.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void productListMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productListMenuActionPerformed
        // TODO add your handling code here:
//        ProductListForm productListForm = new ProductListForm();
//        mainDesktop.add(productListForm);
//        productListForm.setVisible(true);
        
        SwingWorker<Void, Void> worker = new SwingWorker<>() {

            @Override
            protected Void doInBackground() throws Exception {
                // heavy work here (DB, load data)
                return null;
            }

            @Override
            protected void done() {
                ProductListForm productListForm = new ProductListForm();
                mainDesktop.add(productListForm);
                productListForm.setVisible(true);
            }
        };

        worker.execute();
    }//GEN-LAST:event_productListMenuActionPerformed

    private void productCreateMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productCreateMenuActionPerformed
        // TODO add your handling code here:
        ProductCreateForm productCreateForm = new ProductCreateForm();
        mainDesktop.add(productCreateForm);
        productCreateForm.setVisible(true);
    }//GEN-LAST:event_productCreateMenuActionPerformed

    private void menuCreateTransactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCreateTransactionActionPerformed
        // TODO add your handling code here:
        TransactionNewForm transactionCreateForm = new TransactionNewForm();
        mainDesktop.add(transactionCreateForm);
        transactionCreateForm.setVisible(true);
    }//GEN-LAST:event_menuCreateTransactionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JDesktopPane mainDesktop;
    private javax.swing.JMenuItem menuCreateTransaction;
    private javax.swing.JMenuItem productCreateMenu;
    private javax.swing.JMenuItem productListMenu;
    // End of variables declaration//GEN-END:variables
}
