/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.warung;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.HashSet;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.JDesktopPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author fahri
 */
public class ProductListForm extends javax.swing.JInternalFrame implements ProductUpdateForm.ProductUpdateListener {

    Set<Integer> dirtyRows = new HashSet<>();
    
    /**
     * Creates new form ProductListForm
     */
    public ProductListForm() {
        initComponents();
        loadProduct();
    }
    
    @Override
    public void onProductUpdated() {
        loadProduct();
    }
    
    public void loadProduct () {
        DefaultTableModel model = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column) {
                return column != 0; // ID not editable
            }
        };
        
        model.addColumn("ID");
        model.addColumn("Nama Produk");
        model.addColumn("SKU");
        model.addColumn("Stok");
        model.addColumn("Harga");
        
        String sql = "SELECT id, name, sku, stock, price FROM products";
        
        try (Connection conn = DBConnection.getConnection();
            PreparedStatement ps = conn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery()) {

           while (rs.next()) {
               model.addRow(new Object[] {
                   rs.getString("id"),
                   rs.getString("name"),
                   rs.getString("sku"),
                   rs.getLong("stock"),
                   rs.getBigDecimal("price")
               });
           }

           productTable.setModel(model);
           
           model.addTableModelListener(e -> {
               if (e.getType() == javax.swing.event.TableModelEvent.UPDATE) {
                    dirtyRows.add(e.getFirstRow());
                }
           });
           
           dirtyRows.clear();

       } catch (Exception e) {
           e.printStackTrace();
       }
    }
    
    public boolean deleteProductById(long id) {

        String sql = "DELETE FROM products WHERE id = ?";

        try (Connection conn = DBConnection.getConnection();
             PreparedStatement ps = conn.prepareStatement(sql)) {

            ps.setLong(1, id);
            ps.executeUpdate();
            return true;

        } catch (Exception e) {
            e.printStackTrace();
            return false;
        }
    }
    
    public JDesktopPane getDesktopPane() {
        return (JDesktopPane) SwingUtilities.getAncestorOfClass(
            JDesktopPane.class, this
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnCloseProduct = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        productTable = new javax.swing.JTable();
        btnDeleteProduct = new javax.swing.JButton();
        btnSaveChanges = new javax.swing.JButton();
        btnAddProduct = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setText("Daftar Produk");

        btnCloseProduct.setText("Tutup");
        btnCloseProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseProductActionPerformed(evt);
            }
        });

        productTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nama", "Sku", "Stok", "Harga"
            }
        ));
        jScrollPane1.setViewportView(productTable);

        btnDeleteProduct.setText("Hapus Pilihan");
        btnDeleteProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteProductActionPerformed(evt);
            }
        });

        btnSaveChanges.setText("Simpan Perubahan");
        btnSaveChanges.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveChangesActionPerformed(evt);
            }
        });

        btnAddProduct.setText("Tambah Produk");
        btnAddProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProductActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAddProduct))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCloseProduct)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDeleteProduct)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSaveChanges)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnAddProduct))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCloseProduct)
                    .addComponent(btnDeleteProduct)
                    .addComponent(btnSaveChanges))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseProductActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCloseProductActionPerformed

    private void btnDeleteProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteProductActionPerformed
        // TODO add your handling code here:
        int selectedRow = productTable.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this,
                "Pilih data yang akan dihapus",
                "Peringatan",
                JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        // Get ID from column 0
        long id = Long.parseLong(
            productTable.getValueAt(selectedRow, 0).toString()
        );

        // Confirmation dialog
        int confirm = JOptionPane.showConfirmDialog(this,
            "Yakin ingin menghapus produk ini?",
            "Konfirmasi",
            JOptionPane.YES_NO_OPTION
        );

        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        boolean success = deleteProductById(id);

        if (success) {
            JOptionPane.showMessageDialog(this,
                "Produk berhasil dihapus",
                "Sukses",
                JOptionPane.INFORMATION_MESSAGE
            );
            loadProduct();
        } else {
            JOptionPane.showMessageDialog(this,
                "Gagal menghapus produk",
                "Error",
                JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_btnDeleteProductActionPerformed

    private void saveChangesToDatabase() {
        DefaultTableModel model = (DefaultTableModel) productTable.getModel();

        String insertSql = "INSERT INTO products (name, sku, stock, price) VALUES (?, ?, ?, ?)";
        String updateSql = "UPDATE products SET name = ?, sku = ?, stock = ?, price = ? WHERE id = ?";

        try (Connection conn = DBConnection.getConnection();
             PreparedStatement insertPs = conn.prepareStatement(insertSql);
             PreparedStatement updatePs = conn.prepareStatement(updateSql)) {

            conn.setAutoCommit(false);

            for (Integer row : dirtyRows) {
                Object idObj = model.getValueAt(row, 0);

                String name = model.getValueAt(row, 1).toString();
                Object skuObj = model.getValueAt(row, 2);
                String sku = (skuObj != null) ? skuObj.toString() : null;
                long stock = Long.parseLong(model.getValueAt(row, 3).toString());

                Object priceObj = model.getValueAt(row, 4);
                java.math.BigDecimal price =
                    (priceObj instanceof java.math.BigDecimal)
                        ? (java.math.BigDecimal) priceObj
                        : new java.math.BigDecimal(priceObj.toString());

                if (idObj == null) {
                    // INSERT
                    insertPs.setString(1, name);
                    insertPs.setString(2, sku);
                    insertPs.setLong(3, stock);
                    insertPs.setBigDecimal(4, price);
                    insertPs.addBatch();
                } else {
                    // UPDATE
                    long id = Long.parseLong(idObj.toString());
                    updatePs.setString(1, name);
                    updatePs.setString(2, sku);
                    updatePs.setLong(3, stock);
                    updatePs.setBigDecimal(4, price);
                    updatePs.setLong(5, id);
                    updatePs.addBatch();
                }
            }

            insertPs.executeBatch();
            updatePs.executeBatch();
            conn.commit();

            dirtyRows.clear();

            JOptionPane.showMessageDialog(this,
                "Data berhasil disimpan",
                "Sukses",
                JOptionPane.INFORMATION_MESSAGE
            );

            // Reload to get generated IDs
            loadProduct();

        } catch (Exception ex) {
            ex.printStackTrace();

            JOptionPane.showMessageDialog(this,
                "Gagal menyimpan data",
                "Error",
                JOptionPane.ERROR_MESSAGE
            );
        }
    }

    
    private void btnSaveChangesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveChangesActionPerformed
        // TODO add your handling code here:
        if (productTable.isEditing()) {
            productTable.getCellEditor().stopCellEditing();
        }
        
        if (dirtyRows.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Tidak ada perubahan.");
            return;
        }
        
        saveChangesToDatabase();
    }//GEN-LAST:event_btnSaveChangesActionPerformed

    private void btnAddProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProductActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) productTable.getModel();

        // Add empty row (ID = null means NEW DATA)
        model.addRow(new Object[] {
            null,    // ID
            "",      // Nama
            "",      // SKU
            0,       // Stok
            java.math.BigDecimal.ZERO // Harga
        });

        int newRow = model.getRowCount() - 1;
        dirtyRows.add(newRow);

        // Auto focus on new row
        productTable.setRowSelectionInterval(newRow, newRow);
        productTable.editCellAt(newRow, 1);
    }//GEN-LAST:event_btnAddProductActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddProduct;
    private javax.swing.JButton btnCloseProduct;
    private javax.swing.JButton btnDeleteProduct;
    private javax.swing.JButton btnSaveChanges;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable productTable;
    // End of variables declaration//GEN-END:variables
}
